// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0cQKFfz7wsYi9Ppvo5hPfaLbmtJmcC4s',
    appId: '1:306971047268:web:58eadc40f3f8bd20f5f671',
    messagingSenderId: '306971047268',
    projectId: 'basictaskmanager-4f5b2',
    authDomain: 'basictaskmanager-4f5b2.firebaseapp.com',
    databaseURL: 'https://basictaskmanager-4f5b2-default-rtdb.firebaseio.com',
    storageBucket: 'basictaskmanager-4f5b2.appspot.com',
    measurementId: 'G-3XE0SCM7SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFgIHBIgz9KnxyoQUUH3Z1tJHCLWZqYO0',
    appId: '1:306971047268:android:fa9654af8f155f8ef5f671',
    messagingSenderId: '306971047268',
    projectId: 'basictaskmanager-4f5b2',
    databaseURL: 'https://basictaskmanager-4f5b2-default-rtdb.firebaseio.com',
    storageBucket: 'basictaskmanager-4f5b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbt67dr0OWa3kl32epP1wIB3AhCxOetJc',
    appId: '1:306971047268:ios:157d49946185375ff5f671',
    messagingSenderId: '306971047268',
    projectId: 'basictaskmanager-4f5b2',
    databaseURL: 'https://basictaskmanager-4f5b2-default-rtdb.firebaseio.com',
    storageBucket: 'basictaskmanager-4f5b2.appspot.com',
    iosClientId:
        '306971047268-r9gj73g141imf9ohjf0fhogh94vrie2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbt67dr0OWa3kl32epP1wIB3AhCxOetJc',
    appId: '1:306971047268:ios:157d49946185375ff5f671',
    messagingSenderId: '306971047268',
    projectId: 'basictaskmanager-4f5b2',
    databaseURL: 'https://basictaskmanager-4f5b2-default-rtdb.firebaseio.com',
    storageBucket: 'basictaskmanager-4f5b2.appspot.com',
    iosClientId:
        '306971047268-r9gj73g141imf9ohjf0fhogh94vrie2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTaskManager',
  );
}
